swagger: "2.0"
info:
  version: "0.0.1"
  title: User Authentication Microservice
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      errorCode:
        type: number
      message:
        type: string
  UserAuthenticationResponse:
    required:
      - _id
      - name
      - dateCreated
      - lastUsed
    properties:
      _id:
        type: string
      name:
        type: string
      dateCreated:
        type: string
        format: date-time
      lastUsed:
        type: string
        format: date-time
  UserAuthenticationInput:
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string
        format: password
  UserValidationResponse:
    required:
      - userExists
    properties:
      userExists:
        type: boolean
paths:
  /swagger:
    x-swagger-pipe: swagger_raw
  /authentication/register:
    x-swagger-router-controller: authentication
    post:
      description: Registers a user account based on the given credentials
      operationId: register
      parameters:
        - in: body
          name: user
          description: The username and password of the account to register
          required: true
          schema:
            $ref: "#/definitions/UserAuthenticationInput"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UserAuthenticationResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /authentication/login:
    x-swagger-router-controller: authentication
    post:
      description: Authenticates the given user credentials
      operationId: login
      parameters:
        - in: body
          name: user
          description: The username and password of the account to authenticate
          required: true
          schema:
            $ref: "#/definitions/UserAuthenticationInput"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UserAuthenticationResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /authentication/validate/{userId}:
    x-swagger-router-controller: authentication
    get:
      description: Validates if the given user ID is associated with a registered account
      operationId: validateUserId
      parameters:
        - in: path
          name: userId
          description: The user ID to validate
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UserValidationResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"